### ISSUE TITLE
few bugs.

### ISSUE THREAD

**Issue by JourneyOver** [iFelix18/Darkt#3]
Heya, 

Probably know me from my old dark trakt theme (or maybe not) xD but I ended up deprecating my theme as I just never have time to really do a whole lot with it anymore and started pointing people toward your theme in my repository (along with myself using your theme now as well).

Anyways I ran into a few small bugs so far that I'd just thought I'd point out, and this is mainly to due with the dev branch as that is the branch I am testing with mainly (though I will mention if it's broken in the master branch as well or not).

1. (Dev only)
Shows pages are still completely white, dunno if you have gotten around to the show page side of things yet or not in the dev branch but it works fine in the master branch.

2. (Dev and Master)
Both highlighted and quote blocks are completely white, with white text. Highlighted is more of a yellow tint but the text is still completely unreadable.

3. (Dev Only)
Discover page comments section is white as well.

4. (Dev Only)
Liked/Faved List page for users, has a block of white background on both sides of the screen going all the way down, and descriptions that have the "read more" have a white shade to them.

5. (Dev and Master)
The search bar upon opening is white as well (dev branch), on the master branch it flickers white when opening and then shortly after goes dark.

Just a couple of the things I've noticed so far, if I find anymore I will write them down.

Edit: oh also, on dev branch the "ratings-on-trakt" userscript is broken as well.

**Comment by JourneyOver** [comment]
hehe not a problem at all :) 

Ah understood, currently I'm kinda mixing between both master and dev branch (since there was some stuff in the dev branch that I wanted to use like the "hide watch now") and things seem to be working fine for me currently other than of course the 2nd and 5th things I noted above since there was issues in the master branch as well xD.

strange that the userscript things are identical other than the icon/version number, but it does seem like I may of fixed the issue though as I downgraded back to the master version which worked and then back to dev version and it continued to work.. for some reason before hand the ratings just wouldn't show up at all.

**Comment by iFelix18** [comment]
I updated the readme, specifying that the dev version is not currently complete. I hope this limits other possible misunderstandings among users, as you rightly pointed out to me.

**Comment by JourneyOver** [comment]
Just thought I'd comment in my old closed issue instead of creating a whole new issue for a simple question, but are you still working on this? As things seem to be breaking slowly >.< @iFelix18

**Comment by iFelix18** [comment]
Slowly, but yes, I'm still working on it.
