### ISSUE TITLE
invisible text

### ISSUE THREAD

**Issue by lmssieh** [iFelix18/Darkt#35]
![Screenshot_2019-11-17 Dashboard](https://user-images.githubusercontent.com/53446488/69001352-0b622f00-08dd-11ea-89cf-cbbb040ae0d8.png)
![Annotation 2019-11-17 013949](https://user-images.githubusercontent.com/53446488/69001351-07361180-08dd-11ea-942c-45bbbe2d95b2.png)

![image](https://user-images.githubusercontent.com/53446488/69001377-6bf16c00-08dd-11ea-91e7-836d583143e6.png)
![Screenshot_2019-11-17 Dashboard](https://user-images.githubusercontent.com/53446488/69001369-3f3d5480-08dd-11ea-9d3a-4e34051781fe.png)

**Comment by iFelix18** [comment]
Thanks, fixed with Darkt 3.1.3
